server:
  port: 6001

spring:
  profiles:
    active: dev
  application:
    name: enterprise-mcp
  ai:
    mcp:
      server:
        annotation-scanner:
          enabled: true
        enabled: on
        name: mcp-service
        type: sync
        version: 1.0.0
        protocol: streamable
        streamable-http:
          mcp-endpoint: /mcp

# Agent配置
saas:
  saas-server: http://localhost:8001
  tenant-server: http://localhost:8002
  tenant-id: 10000
  verify:
    timestamp-skew-seconds: 300
    nonce-ttl-seconds: 300

rag:
  # 知识库配置
  url: http://localhost:9621
